# Generated by Django 5.1.15 on 2026-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="mitre_tactics",
            field=models.JSONField(
                default=list,
                help_text="List of MITRE Tactics (e.g., Execution, Persistence)",
            ),
        ),
    ]
