# Generated by Django 5.1.15 on 2026-02-01 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
        ("events", "0002_event_mitre_tactics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status_change_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for the latest status change (e.g. why FP/TP)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSING", "Processing"),
                    ("TRIAGED", "Triaged"),
                    ("FALSE_POSITIVE", "False Positive"),
                    ("TRUE_POSITIVE", "True Positive"),
                    ("PROMOTED", "Promoted to Incident"),
                    ("CLOSED", "Closed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChartDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("BAR", "Bar Chart"),
                            ("LINE", "Line Chart"),
                            ("PIE", "Pie Chart"),
                            ("TABLE", "Table"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "query_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for the query (filters, grouping)",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Visible to all users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Markdown enabled analyst notes"
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                (
                    "timeline",
                    models.JSONField(default=list, help_text="List of timeline events"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation",
                        to="events.event",
                    ),
                ),
                (
                    "indicators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="investigations",
                        to="artifacts.indicator",
                    ),
                ),
                (
                    "related_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_investigations",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
