# Generated by Django 5.2.10 on 2026-02-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=512, unique=True)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("IP", "IP Address"),
                            ("HASH", "File Hash"),
                            ("DOMAIN", "Domain"),
                            ("URL", "URL"),
                            ("EMAIL", "Email Address"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "related_events",
                    models.ManyToManyField(
                        related_name="indicators", to="events.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of this evidence (e.g. VirusTotal, Splunk)",
                        max_length=100,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="The full raw response/report"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("MALICIOUS", "Malicious"),
                            ("SUSPICIOUS", "Suspicious"),
                            ("BENIGN", "Benign"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="events.incident",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="artifacts.indicator",
                    ),
                ),
            ],
        ),
    ]
