# Generated by Django 5.1.15 on 2026-02-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
        ("events", "0003_event_status_change_reason_alter_event_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="events.event",
            ),
        ),
    ]
